services:
  printer-ui:
    image: printer-ui:local
    container_name: printer-ui
    ports:
      - "3000:3000"
    depends_on:
      - zplbox
    environment:
      - ZPLBOX_URL=http://zplbox:8080

  zplbox:
    build:
      context: ./zplbox
      dockerfile: Dockerfile
      args:
        VERSION: "1.0.0"
    image: zplbox:local
    container_name: zplbox
    restart: unless-stopped
    ports:
      - "8080:8080"
