version: "3.9"
services:
  printer-ui:
    build: .
    container_name: printer-ui
    ports:
      - "3000:3000"
    environment:
      - PRINTER_URL=http://192.168.0.27:80/Integration/print/Execute
