services:
  printer-ui:
    build:
      context: .
      dockerfile: Dockerfile
    image: printer-ui:local
    container_name: printer-ui
    ports:
      - "3000:3000"
    depends_on:
      - zplbox
    environment:
      - ZPLBOX_URL=http://zplbox:8080
      - APP_DATA_DIR=/data

      # Host-Updater (UI trigger)
      - UPDATER_BASE_URL=http://host.docker.internal:9123
      - UPDATER_TOKEN=CHANGE_ME_LONG_RANDOM_TOKEN

    extra_hosts:
      - "host.docker.internal:host-gateway"

    volumes:
      - printer-ui-data:/data

  zplbox:
    build:
      context: ./zplbox
      dockerfile: Dockerfile
      args:
        VERSION: "1.0.0"
    image: zplbox:local
    container_name: zplbox
    restart: unless-stopped
    ports:
      - "8080:8080"

volumes:
  printer-ui-data:
